### ISSUE TITLE
Why did you fork this add-on?

### ISSUE THREAD

**Issue by etoulas** [etbusch/web-developer-form-filler-ext#17]
- Was it necessary in order to provide a Firefox add-on? (that's how I found it anyway)

- What have you modified compared to the upstream?

- Do you keep your fork in sync with upstream? (why wasn't it possible to contribute via a PR?)

**Comment by etbusch** [comment]
Hi!

Your questions are answered below:

> Was it necessary to provide a Firefox add-on? (that's how I found it anyway)

Yes, initially there were some minor extension API incompatibilities, as well as additional manifest properties needed for submission to the Firefox Addon store.

> What have you modified compared to the upstream?

Quite a bit, feel free to browse the commit log, but in short I have:

* Upgraded jQuery and Bootstrap to more recent versions
* Migrated from localStorage to Sync, so saved forms are synced across browsers with the same FF account
* Performed general UI and functionality improvements, and a few bug fixes

> Do you keep the your fork in sync with upstream?

I have manually brought in changes from upstream, but there have been very few commits since the fork.

> why wasn't it possible to contribute via a PR?

I considered the upstream project abandoned. It had been over 2 years since the original owner had updated the project, and the issue I submitted for FF support had gone unanswered for over a year. I personally switched to FF from chrome, and wanted to bring this extension with me, so I did.

Let me know if you have any other questions!

**Comment by etoulas** [comment]
Thanks, Eric! You've adequatly answered my questions.

> I personally switched to FF from chrome, and wanted to bring this extension with me, so I did.

I appreciate that. Keep up the good work.

May I suggest to put this Q&A right into the readme?
