### ISSUE TITLE
URL cares about query params?

### ISSUE THREAD

**Issue by delboy1978uk** [etbusch/web-developer-form-filler-ext#2]
Does this extension take query params into consideration?

I'm working on the same page, but sometimes have different GET parameters. When that happens, none of my saved forms can be restored.

The answer would be to trim everything after the `?`

Great little extension btw!

**Comment by etbusch** [comment]
Hey @delboy1978uk,

By default the extension filters saved sets by the full URL, but you can set a different filter in the popup gear menu:

- "Filter by domain" ignores protocol, path, and query parameters
- "Filter by path" ignores query parameters
- "Filter by full URL" listens to the entire URL

You should be able to "Filter by path" and see the behavior you want.

I plan on adding a wiki to document the features of this extension better.

Thanks! It has helped me a ton over the years, and since the original is abandoned, I hope to breathe some new life into it.
